---
- name: activity
  become: yes
  hosts: all
  tasks: 
    - name: install apache
      ansible.builtin.apt:
        name:
          - apache2
          - nginx
        state: present
        update_cache: yes
